ALTER SESSION SET NLS_DATE_FORMAT = 'YY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YY-MM-DD HH24:MI:SS.FF6';
SPOOL data/temp.txt
SELECT * FROM AZAREA.EMBULK_OUTPUT ORDER BY ID;
SPOOL OFF

EXIT;
