DROP TABLE EMBULK_OUTPUT;

CREATE TABLE EMBULK_OUTPUT (
    ID     DECIMAL(4),
    NUM    DECIMAL(12,2),
    STR    CHAR(8),
    VARSTR VARCHAR2(8),
    NSTR    NCHAR(8),
    NVARSTR NVARCHAR2(8),
    PRIMARY KEY(ID)
);

EXIT;
