DROP TABLE AZAREA.EMBULK_OUTPUT;

CREATE TABLE AZAREA.EMBULK_OUTPUT (
    ID     DECIMAL(4),
    NUM    DECIMAL(12,2),
    STR    CHAR(8),
    VARSTR VARCHAR2(8),
    DT     DATE,
    DTTM0  TIMESTAMP,
    DTTM3  TIMESTAMP(3),
    PRIMARY KEY(ID)
);

EXIT;
