DROP TABLE EMBULK_OUTPUT;

CREATE TABLE EMBULK_OUTPUT (
    ID     INT,
    NUM    DECIMAL(12,2),
    STR    CHAR(8),
    VARSTR VARCHAR(8),
    DT     DATE,
    DTTM   DATETIME,
    DTTM2  DATETIME2,
    SDTTM   SMALLDATETIME,
    PRIMARY KEY(ID)
);
